name = input("Enter a name: ")
colour = input("Enter a colour: ")
drink = input("Enter a drink: ")
object = input("Enter a object: ")
person = input("Enter a name: ")
adjective1 = input("Enter a adjective: ")
adjective2 = input("Enter a adjective: ")
noun = input("Enter a noun: ")
adjective3 = input("Enter a adverb: ")
celebrity = input("Enter a celebrity: ")
location = input("Enter a location: ")
direction = input("Enter a direction: ")

print(f"\n\n{name} is sick with the {colour} flu.")
print(f"Drink more {drink} and take {object} as needed.")
print(f"Yesterday, {person} and {name} went to the park.")
print(f"On our way to the {adjective1} park, we saw a {adjective2} {noun} bike.")
print(f"We also saw big {adjective3} balloons tied to {celebrity}.")
print(f"Once we got to the {location}, the sky turned {direction}.")